name: cleaning_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  nb_utils: ^6.1.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/images/svg/
    - assets/dummy/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic